os: Visual Studio 2017
version: 1.0.0.{build}

install:
    # https://www.appveyor.com/docs/windows-images-software/
    - set QTDIR=C:\Qt\5.12\msvc2017_64
    - set PATH=%QTDIR%\bin;%PATH%
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - qmake -v

build_script:
    - qmake
    - nmake /NOLOGO

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\projects\lib\tests\
    - qmake
    - nmake /NOLOGO
    - '%cd%\chessboard\release\tst_board'
    - '%cd%\mersenne\release\tst_mersenne'
    - cd polyglotbook & release\tst_polyglotbook & cd..
    - '%cd%\sprt\release\tst_sprt'
    - '%cd%\tournamentpair\release\tst_tournamentpair'
    - '%cd%\tournamentplayer\release\tst_tournamentplayer'
    - '%cd%\pipereader\release\tst_pipereader'
    - cd %APPVEYOR_BUILD_FOLDER%\projects\lib\components\json\tests\
    - qmake
    - nmake /NOLOGO
    - cd parser & release\tst_jsonparser & cd..
    - cd serializer & release\tst_jsonserializer & cd..

artifacts:
  - path: projects\cli\cutechess-cli.exe
    name: cutechess-cli
  - path: projects\gui\cutechess.exe
    name: cutechess
